extern musHandle sndHandle;
extern musHandle sndHandle_pyoro1;
extern musHandle sndHandle_pyoro2;

#define SND_BLOCK_DIE           0
#define SND_PYORO_WALK          1
#define SND_PYORO_DIE           2
#define SND_BEAN_GET            3
#define SND_TONGUE_IN           4
#define SND_TONGUE_OUT          5
#define SND_ANGEL_DOWN          6
#define SND_ANGEL_REPAIR        7
#define SND_COMET               8
#define SND_BEAN_POP            9
#define SND_PAUSE               10
#define SND_UNPAUSE             11
#define SND_MENU_BACK           12
#define SND_MENU_CHANGE         13
#define SND_MENU_SELECT         14
#define SND_GAME_START          15
#define SND_BEAN_DIE1           16
#define SND_BEAN_DIE2           17
#define SND_BEAN_DIE3           18
#define SND_BEAN_DIE4           19
#define SND_SPIT                20