// Generated by Nintendo 64 Texture Converter
// By buu342
// Size = 8x8
// Type = 4-Bit Color Index (G_IM_FMT_CI)

#include <ultra64.h>
#include "bac_bordercorner.h"

static Gfx bac_bordercorner_C_dummy_aligner1[] = { gsSPEndDisplayList() };
unsigned char bac_bordercorner[] = {
    0x00, 0x00, 0x00, 0x00, 
    0x00, 0x01, 0x11, 0x11, 
    0x00, 0x11, 0x11, 0x11, 
    0x01, 0x11, 0x11, 0x11, 
    0x01, 0x11, 0x11, 0x11, 
    0x01, 0x11, 0x11, 0x22, 
    0x01, 0x11, 0x12, 0x33, 
    0x01, 0x11, 0x12, 0x33, 
};

static Gfx bac_bordercorner_tlut_C_dummy_aligner1[] = { gsSPEndDisplayList() };
unsigned short bac_bordercorner_tlut[] = {
    GPACK_RGBA5551(32, 32, 72, 1),  0xFFFF, 0x01, 0x07FE
};