// Generated by Nintendo 64 Texture Converter
// By buu342
// Size = 8x8
// Type = 4-Bit Color Index (G_IM_FMT_CI)

#include <ultra64.h>
#include "spr_block.h"

static Gfx spr_block_C_dummy_aligner1[] = { gsSPEndDisplayList() };
unsigned char spr_block[] = {
    0x01, 0x11, 0x11, 0x12, 
    0x30, 0x00, 0x00, 0x01, 
    0x30, 0x00, 0x00, 0x01, 
    0x30, 0x00, 0x00, 0x01, 
    0x30, 0x00, 0x00, 0x01, 
    0x30, 0x00, 0x00, 0x01, 
    0x30, 0x00, 0x00, 0x01, 
    0x43, 0x33, 0x33, 0x30, 
};

static Gfx spr_block_tlut_C_dummy_aligner1[] = { gsSPEndDisplayList() };
unsigned short spr_block_tlut[] = {
    0x8C5B, 0xB5A9, 0xFFFF, 0x01, 0x01,
};

static Gfx spr_block_tlut_beige_C_dummy_aligner1[] = { gsSPEndDisplayList() };
unsigned short spr_block_tlut_beige[] = {
    0x8C17, 0xB565, 0xFFFF, 0x01, 0x01,
};

static Gfx spr_block_tlut_dark_C_dummy_aligner1[] = { gsSPEndDisplayList() };
unsigned short spr_block_tlut_dark[] = {
    0x01, 0xFFFF, 0x01, 0xFFFF, 0x01,
};